/// Flutter icons SeverMetropol
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SeverMetropol
///      fonts:
///       - asset: fonts/SeverMetropol.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SeverMetropol {
  SeverMetropol._();

  static const _kFontFam = 'SeverMetropol';
  static const String? _kFontPkg = null;

  static const IconData Icon_Account_Circle = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Add = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Add_to_Cart = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Add_to_Shopping_Bag = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Attach_File = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Calendar_Today = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Delete = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Delete_Forever = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Direction = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Check = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Check_Doubled = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Checkbox_Checked = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Checkbox_Unchecked = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Clear = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Close = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Contact_Support = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_East = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Edit = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Expand_Less = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Expand_More = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Favorite = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Favorite_Outlined = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Filter_List = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Grid_View = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_History = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Info = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_List = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Logout = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Lock = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Navigate_Before = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Navigate_Next = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_North = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Notification = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_More_Horizontal = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Open_VPN = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Photo_Camers = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Place = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Present = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_QR_Code_Scanner = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Question_Answer = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Radio_Button_Checked = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Radio_Button_Unhecked = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Redeem_Card = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Remove = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Search = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Share = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Shopping_Bag = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Site = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Special_Offer = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Special_Offer_Alt = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Star_Rate = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_Star_Rate_Outlined = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Icon_West = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
