// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3kpy7j5LezRJKD1aFCxZqBYi4C7whHU',
    appId: '1:1030265242658:android:8cb201f286b01b8115f67b',
    messagingSenderId: '1030265242658',
    projectId: 'art-navsegda',
    databaseURL: 'https://art-navsegda.firebaseio.com',
    storageBucket: 'art-navsegda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyl2OoIPnZXwfZIa8szugS04p475N9u8',
    appId: '1:1030265242658:ios:fc6a0a9849d37a1a15f67b',
    messagingSenderId: '1030265242658',
    projectId: 'art-navsegda',
    databaseURL: 'https://art-navsegda.firebaseio.com',
    storageBucket: 'art-navsegda.appspot.com',
    iosClientId: '1030265242658-rd3h2kb0pd63din9bp6r4qv8p71escbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirebase',
  );
}
